const workoutData = [
    {
        id: 1,
        title: 'Push-ups',
        details: 'Perform a full push-up with proper form for 30 seconds.',
        image: require('../../assets/workouts/pngs/push-ups.png'),
        gifImage: require('../../assets/workouts/gifs/push-ups.gif'),
        timing: '30 seconds',
        category: 'Strength',
    },
    {
        id: 2,
        title: 'Squats',
        details: 'Perform bodyweight squats with proper form for 45 seconds.',
        image: require('../../assets/workouts/pngs/squat.png'),
        gifImage: require('../../assets/workouts/gifs/squat.gif'),
        timing: '45 seconds',
        category: 'Strength',
    },
    {
        id: 3,
        title: 'Jumping Jacks',
        details: 'Perform jumping jacks for 1 minute.',
        image: require('../../assets/workouts/pngs/jumping-jacks.png'),
        gifImage: require('../../assets/workouts/gifs/jumping-jacks.gif'),
        timing: '60 seconds',
        category: 'Cardio',
    },
    {
        id: 4,
        title: 'Plank',
        details: 'Hold a plank position for 1 minute.',
        image: require('../../assets/workouts/pngs/plank.png'),
        gifImage: require('../../assets/workouts/gifs/plank.gif'),
        timing: '60 seconds',
        category: 'Core',
    },
    {
        id: 5,
        title: 'Lunges',
        details: 'Perform alternating lunges for 40 seconds.',
        image: require('../../assets/workouts/pngs/lunges.png'),
        gifImage: require('../../assets/workouts/gifs/lunges.gif'),
        timing: '40 seconds',
        category: 'Strength',
    },
    {
        id: 6,
        title: 'High Knees',
        details: 'Run in place with high knees for 50 seconds.',
        image: require('../../assets/workouts/pngs/high-knees.png'),
        gifImage: require('../../assets/workouts/gifs/high-knees.gif'),
        timing: '50 seconds',
        category: 'Cardio',
    },
    {
        id: 7,
        title: 'Bicycle Crunches',
        details: 'Perform bicycle crunches for 1 minute.',
        image: require('../../assets/workouts/pngs/bicycle-crunches.png'),
        gifImage: require('../../assets/workouts/gifs/bicycle-crunches.gif'),
        timing: '60 seconds',
        category: 'Core',
    },
    {
        id: 8,
        title: 'Mountain Climbers',
        details: 'Perform mountain climbers for 30 seconds.',
        image: require('../../assets/workouts/pngs/mountain-climbers.png'),
        gifImage: require('../../assets/workouts/gifs/mountain-climbers.gif'),
        timing: '30 seconds',
        category: 'Cardio',
    },
    {
        id: 9,
        title: 'Dead Bug',
        details: 'Perform a dead bug exercise for 45 seconds.',
        image: require('../../assets/workouts/pngs/dead-bug.png'),
        gifImage: require('../../assets/workouts/gifs/dead-bug.gif'),
        timing: '45 seconds',
        category: 'Core',
    },
    {
        id: 10,
        title: 'Burpees',
        details: 'Perform burpees with a jump for 1 minute.',
        image: require('../../assets/workouts/pngs/burpees.png'),
        gifImage: require('../../assets/workouts/gifs/burpees.gif'),
        timing: '60 seconds',
        category: 'Cardio',
    },
    {
        id: 11,
        title: 'Shoulder Taps',
        details: 'Perform shoulder taps in a plank position for 30 seconds.',
        image: require('../../assets/workouts/pngs/shoulder-taps.png'),
        gifImage: require('../../assets/workouts/gifs/shoulder-taps.gif'),
        timing: '30 seconds',
        category: 'Core',
    },
    {
        id: 12,
        title: 'Dumbbell Rows',
        details: 'Perform dumbbell rows for 40 seconds.',
        image: require('../../assets/workouts/pngs/dumbbell-rows.png'),
        gifImage: require('../../assets/workouts/gifs/dumbbell-rows.gif'),
        timing: '40 seconds',
        category: 'Strength',
    },
];

export default workoutData;
