const workoutData = [
    {
        id: 1,
        title: 'Push-ups',
        details: 'Perform a full push-up with proper form for 30 seconds.',
        image: require('../../assets/workouts/pngs/push-ups.png'),
        gifImage: require('../../assets/workouts/gifs/push-ups.gif'),
        timing: '30 seconds',
        category: 'Strength',
    },
    {
        id: 2,
        title: 'Squats',
        details: 'Perform bodyweight squats with proper form for 45 seconds.',
        image: require('../../assets/workouts/pngs/squat.png'),
        gifImage: require('../../assets/workouts/gifs/squat.gif'),
        timing: '45 seconds',
        category: 'Strength',
    },
    {
        id: 3,
        title: 'Jumping Jacks',
        details: 'Perform jumping jacks for 1 minute.',
        image: require('../../assets/workouts/pngs/jumping-jacks.png'),
        gifImage: require('../../assets/workouts/gifs/jumping-jacks.gif'),
        timing: '60 seconds',
        category: 'Cardio',
    },
    {
        id: 4,
        title: 'Plank',
        details: 'Hold a plank position for 1 minute.',
        image: require('../../assets/workouts/pngs/plank.png'),
        gifImage: require('../../assets/workouts/gifs/plank.gif'),
        timing: '60 seconds',
        category: 'Core',
    },
    {
        id: 5,
        title: 'Lunges',
        details: 'Perform alternating lunges for 40 seconds.',
        image: require('../../assets/workouts/pngs/lunges.png'),
        gifImage: require('../../assets/workouts/gifs/lunges.gif'),
        timing: '40 seconds',
        category: 'Strength',
    },
    {
        id: 6,
        title: 'High Knees',
        details: 'Run in place with high knees for 50 seconds.',
        image: require('../../assets/workouts/pngs/high-knees.png'),
        gifImage: require('../../assets/workouts/gifs/high-knees.gif'),
        timing: '50 seconds',
        category: 'Cardio',
    },
    {
        id: 7,
        title: 'Bicycle Crunches',
        details: 'Perform bicycle crunches for 1 minute.',
        image: require('../../assets/workouts/pngs/bicycle-crunches.png'),
        gifImage: require('../../assets/workouts/gifs/bicycle-crunches.gif'),
        timing: '60 seconds',
        category: 'Core',
    },
    {
        id: 8,
        title: 'Mountain Climbers',
        details: 'Perform mountain climbers for 30 seconds.',
        image: require('../../assets/workouts/pngs/mountain-climbers.png'),
        gifImage: require('../../assets/workouts/gifs/mountain-climbers.gif'),
        timing: '30 seconds',
        category: 'Cardio',
    },
    {
        id: 9,
        title: 'Dead Bug',
        details: 'Perform a dead bug exercise for 45 seconds.',
        image: require('../../assets/workouts/pngs/dead-bug.png'),
        gifImage: require('../../assets/workouts/gifs/dead-bug.gif'),
        timing: '45 seconds',
        category: 'Core',
    },
    {
        id: 10,
        title: 'Burpees',
        details: 'Perform burpees with a jump for 1 minute.',
        image: require('../../assets/workouts/pngs/burpees.png'),
        gifImage: require('../../assets/workouts/gifs/burpees.gif'),
        timing: '60 seconds',
        category: 'Cardio',
    },
    {
        id: 11,
        title: 'Shoulder Taps',
        details: 'Perform shoulder taps in a plank position for 30 seconds.',
        image: require('../../assets/workouts/pngs/shoulder-taps.png'),
        gifImage: require('../../assets/workouts/gifs/shoulder-taps.gif'),
        timing: '30 seconds',
        category: 'Core',
    },
    {
        id: 12,
        title: 'Dumbbell Rows',
        details: 'Perform dumbbell rows for 40 seconds.',
        image: require('../../assets/workouts/pngs/dumbbell-rows.png'),
        gifImage: require('../../assets/workouts/gifs/dumbbell-rows.gif'),
        timing: '40 seconds',
        category: 'Strength',
    },
];

const nutritionData = [
    {
        id: 1,
        name: 'Apple',
        details: 'A medium apple contains about 95 calories, is high in fiber, and supports digestion.',
        image: require('../../assets/nutritions/pngs/apple.png'),
        benefits: 'Rich in antioxidants, supports heart health, and aids in weight management.',
    },
    {
        id: 2,
        name: 'Banana',
        details: 'A medium banana has about 105 calories, is rich in potassium, and boosts energy.',
        image: require('../../assets/nutritions/pngs/banana.png'),
        benefits: 'Supports muscle function, prevents cramps, and aids digestion.',
    },
    {
        id: 3,
        name: 'Broccoli',
        details: 'One cup of broccoli contains 55 calories and is packed with vitamins C and K.',
        image: require('../../assets/nutritions/pngs/broccoli.png'),
        benefits: 'Improves immunity, supports bone health, and is rich in fiber.',
    },
    {
        id: 4,
        name: 'Almonds',
        details: 'A handful of almonds provides 160 calories and healthy fats.',
        image: require('../../assets/nutritions/pngs/almonds.png'),
        benefits: 'Supports brain health, improves skin quality, and boosts energy.',
    },
    {
        id: 5,
        name: 'Salmon',
        details: 'Salmon is rich in omega-3 fatty acids and has about 200 calories per 3-ounce serving.',
        image: require('../../assets/nutritions/pngs/salmon.png'),
        benefits: 'Promotes brain health, reduces inflammation, and supports heart health.',
    },
    {
        id: 6,
        name: 'Spinach',
        details: 'One cup of spinach has only 23 calories and is rich in iron and calcium.',
        image: require('../../assets/nutritions/pngs/spinach.png'),
        benefits: 'Boosts immunity, improves bone health, and promotes healthy skin.',
    },
    {
        id: 7,
        name: 'Eggs',
        details: 'One large egg contains about 70 calories and is a great source of protein.',
        image: require('../../assets/nutritions/pngs/eggs.png'),
        benefits: 'Supports muscle repair, boosts brain health, and is nutrient-dense.',
    },
    {
        id: 8,
        name: 'Carrots',
        details: 'One cup of carrots contains about 50 calories and is high in vitamin A.',
        image: require('../../assets/nutritions/pngs/carrots.png'),
        benefits: 'Supports eye health, improves skin, and strengthens immunity.',
    },
    {
        id: 9,
        name: 'Blueberries',
        details: 'A cup of blueberries has 84 calories and is packed with antioxidants.',
        image: require('../../assets/nutritions/pngs/blueberries.png'),
        benefits: 'Supports brain function, improves memory, and reduces inflammation.',
    },
    {
        id: 10,
        name: 'Greek Yogurt',
        details: 'One cup of Greek yogurt contains about 100 calories and is rich in probiotics.',
        image: require('../../assets/nutritions/pngs/greek-yogurt.png'),
        benefits: 'Supports gut health, strengthens bones, and is a good protein source.',
    },
    {
        id: 11,
        name: 'Sweet Potato',
        details: 'One medium sweet potato has about 112 calories and is rich in beta-carotene.',
        image: require('../../assets/nutritions/pngs/sweet-potato.png'),
        benefits: 'Improves eye health, boosts immunity, and supports digestion.',
    },
    {
        id: 12,
        name: 'Avocado',
        details: 'Half an avocado contains about 120 calories and healthy fats.',
        image: require('../../assets/nutritions/pngs/avocado.png'),
        benefits: 'Promotes heart health, improves skin, and helps in nutrient absorption.',
    },
];

const exercises = [
    { id: '1', title: 'Chest Workout', image: require('../../assets/images/chest.png') },
    { id: '2', title: 'Back Workout', image: require('../../assets/images/back.png') },
    { id: '3', title: 'Lower Leg Workout', image: require('../../assets/images/lowerLegs.png') },
    { id: '4', title: 'Upper Leg Workout', image: require('../../assets/images/upperLegs.png') },
    { id: '5', title: 'Lower Arm Workout', image: require('../../assets/images/lowerArms.png') },
    { id: '6', title: 'Upper Arm Workout', image: require('../../assets/images/upperArms.png') },
    { id: '7', title: 'Shoulder Workout', image: require('../../assets/images/shoulders.png') },
    { id: '8', title: 'Neck Workout', image: require('../../assets/images/neck.png') },
    { id: '9', title: 'Waist Workout', image: require('../../assets/images/waist.png') },
];

export { workoutData, nutritionData, exercises };
